# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_auto_20170705_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_in_time', models.TimeField()),
                ('punch_in_notes', models.CharField(max_length=250)),
                ('punch_out_time', models.TimeField()),
                ('punch_out_notes', models.CharField(max_length=250)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.Employee')),
            ],
        ),
    ]
