# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_notes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_notes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_time',
            field=models.TimeField(blank=True),
        ),
    ]
