# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0005_auto_20170710_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_notes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_notes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_time',
            field=models.TimeField(null=True),
        ),
    ]
