# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_auto_20170711_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_in_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_in_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='punch_out_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
