# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_auto_20170712_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='notes',
            new_name='punch_in_notes',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='punch_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_notes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_time',
            field=models.TimeField(null=True),
        ),
    ]
