# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0010_auto_20170715_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
