# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0011_attendance_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.DurationField(null=True),
        ),
    ]
